### ISSUE TITLE
Support for text to narrate the journey

### ISSUE THREAD

**Issue by treeplate** [treeplate/forest_venture#17]
treeplate/cone_of_sight and treeplate/explorer have this feature, you can just use one of their code for easiness

**Comment by Hixie** [comment]
maps have thresholds which trigger messages
thresholds have IDs
messages are in order and have IDs
initially, the first message is the next message due
when a message is shown, the next message due becomes the next one in the list
if you pass a threshold, you the message with that ID is shown if it's the next message due

**Comment by Hixie** [comment]
IDs are lowercase letters
